GET http://localhost:9000/database-queries/recommended-channels
###
curl -X POST -H "Content-Type: application/json" -d '{"query": "daniyedss"}' http://localhost:9000/database-queries/search-query

###
curl -X POST -H "Content-Type: application/json" -d '{"username": "usoa", "email":"usoa@hotmail.com", "passphrase":"12345678"}' http://localhost:9000/database-queries/create-new-user

###
curl -X POST -H "Content-Type: application/json" -d '{"user_id": 1,"subject_user_id": 7, "activity_type": "POST","content": "YEA GAIS LUUhK"}' http://localhost:9000/database-queries/activities




###
GET http://localhost:9000/user/refresh/Dani

### 
POST http://localhost:9000/user/test
Content-Type: application/json

{
    "deez": "ss"
}

###
GET http://localhost:9000/user/encode-token/123
### 
POST http://localhost:9000/user/decode-token
Content-Type: application/json

{
    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MTMsImV4cCI6MTY5MTI2NDAyOX0.1kVzHW1T7YHA7tY_300oGgwTLBpU-UcHzfYrS6hPB60"
}

###
GET http://localhost:9000/user/protected 
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MTMsImV4cCI6MTY5MTI2NDAyOX0.1kVzHW1T7YHA7tY_300oGgwTLBpU-UcHzfYrS6hPB60

###
GET http://localhost:9000/database-queries/test-db

###
POST http://localhost:9000/database-queries/test-db/daniyed

###
POST http://localhost:9000/database-queries/